# _config.yml for GitHub Pages (Jekyll)

title: "SLOVENSKO3"
description: "Slovensko3 – Občianska komunita pre budúcnosť Slovenska"
theme: minima
# theme: architect
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: cayman

# Base settings
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: if you want to exclude folders/files
# exclude:
#   - node_modules
#   - vendor
