name: Trigger GitHub Pages rebuild

on:
  push:
    branches:
      - main

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make empty commit to force GitHub Pages rebuild
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit --allow-empty -m "Trigger GitHub Pages rebuild"
          git push
